name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    env:
      DB_DATABASE: halodepot

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: halodepot
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install Yarn Dependencies
      run: yarn install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Asset Packaging
      run: yarn run dev
    - name: PHPCS
      run: vendor/bin/phpcs
    - name: Do migrations
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: vendor/bin/phpunit
    - name: Run Deployment
      shell: bash
      if: github.ref == 'refs/heads/master'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_SECRET_KEY }}
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p $HOME/.ssh
        echo -e "StrictHostKeyChecking no" >> $HOME/.ssh/config
        echo -e "ForwardAgent yes" >> $HOME/.ssh/config
        eval $(ssh-agent -s)
        echo "${SSH_PRIVATE_KEY}" | base64 -d | ssh-add -
        php artisan deploy --vvv
